# pseudo-dodo-pizza просмотр ассортимента какого-либо предприятия.
# Copyright (C) 2024 Vladimir Leonidovich
#
# This program is free software: you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# [ ](governance): CC-BY

name: 'CI/CD: Dodo Pizza'
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: npm clean-install
      - run: npx nx build pseudo-dodo-pizza
        env:
          ESB_CONFIGURATION: ${{vars.ESB_CONFIGURATION}}
          ESB_ASSORTMENT: ${{vars.ESB_ASSORTMENT}}
      - run: mv _site/browser/* _site
      - uses: actions/upload-pages-artifact@v3
        with:
          retention-days: 90
  deployment:
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - uses: actions/deploy-pages@v4

    permissions:
      id-token: write
      pages: write
    environment:
      name: Production
